# Generated by Django 2.2.3 on 2019-07-15 17:39

from django.db import migrations, models
import vue_plugins.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VuePlugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=512)),
                ('repo_url', models.TextField(max_length=1024)),
                ('has_demo', models.IntegerField(validators=[vue_plugins.validators.validate_zero_or_greater, vue_plugins.validators.validate_one_or_less])),
                ('has_meaningful_tests', models.IntegerField(validators=[vue_plugins.validators.validate_zero_or_greater, vue_plugins.validators.validate_one_or_less])),
                ('has_example_code', models.IntegerField(validators=[vue_plugins.validators.validate_zero_or_greater, vue_plugins.validators.validate_one_or_less])),
                ('has_api_documented', models.IntegerField(validators=[vue_plugins.validators.validate_zero_or_greater, vue_plugins.validators.validate_one_or_less])),
                ('has_ci', models.IntegerField(validators=[vue_plugins.validators.validate_zero_or_greater, vue_plugins.validators.validate_one_or_less])),
                ('last_release_date', models.DateField(blank=True, null=True)),
                ('num_commits_recently', models.IntegerField(default=0)),
                ('num_contributors', models.IntegerField(default=0)),
                ('num_downloads', models.IntegerField(default=0)),
                ('num_stars', models.IntegerField(default=0)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]
