# Generated by Django 2.2.3 on 2019-07-15 18:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vue_plugins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vueplugin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vueplugin',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vueplugin',
            name='repo_url',
            field=models.URLField(max_length=1024),
        ),
    ]
