# Generated by Django 2.2.3 on 2019-07-15 19:49

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('vue_plugins', '0002_auto_20190715_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='vueplugin',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
