# Generated by Django 2.2.4 on 2019-08-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue_plugins', '0003_auto_20190715_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='vueplugin',
            name='description',
            field=models.TextField(blank=True, max_length=512),
        ),
    ]
