# Generated by Django 2.2.4 on 2019-08-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue_plugins', '0005_auto_20190823_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='vueplugin',
            name='npm_package_name',
            field=models.TextField(blank=True, max_length=512),
        ),
    ]
