# Generated by Django 2.2.4 on 2019-08-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue_plugins', '0006_vueplugin_npm_package_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vueplugin',
            name='last_release_name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
