# Generated by Django 2.2.4 on 2019-08-23 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vue_plugins', '0007_vueplugin_last_release_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vueplugin',
            old_name='last_release_name',
            new_name='last_release_tag_name',
        ),
    ]
