# Generated by Django 2.2.4 on 2019-08-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue_plugins', '0008_auto_20190823_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='vueplugin',
            name='repo_readme',
            field=models.URLField(blank=True, max_length=1024),
        ),
    ]
