# Generated by Django 2.2.4 on 2019-08-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue_plugins', '0011_auto_20190823_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vueplugin',
            name='repo_license_name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
